name: Bug report
description: Create a report to help us improve or fix something
labels: ['bug', 'need repro']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please give us a brief summary of the issue you're experiencing.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: What would we have to do in order to reproduce this issue?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What is expected to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What is actually happening?
    validations:
      required: true
  - type: input
    id: updated
    attributes:
      label: Last Updated
      description: When did you last update this resource?
      placeholder: e.g. last week, today
    validations:
      required: true
  - type: input
    id: artifact
    attributes:
      label: FiveM Artifact
      description: Which version of the FiveM artifact are you using?
      placeholder: e.g. 7290, 10748, 12735
    validations:
      required: true
  - type: input
    id: modified
    attributes:
      label: Modified
      description: Have you modified the resource in any way? If so, how?
      placeholder: e.g. added new features, removed features
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional comments
      description: If you have any additional comments or information which might better help us understand the issue, please provide it here.