name: Feature request
description: Suggest an idea
labels: enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please give us a detailed summary of the feature or enhancement you're proposing and how it would benefit the community.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional comments
      description: If you have any additional comments or information which might better help us understand the request, please provide it here.
